### ISSUE TITLE
Are you perhaps collecting visual novel engine?

### ISSUE THREAD

**Issue by Cosetto** [2439905184/Galgame-Engine-Collect#34]
I got Artemis and Yuris SDK(This Yuris has emote support) from my friend and also these 
![image](https://user-images.githubusercontent.com/81801486/180637744-e068ad9b-0b83-4757-bc33-0b2af8b0f49a.png)
But unfortunately he had deleted them all but I still lucky enough to download 2 of the engines
Artemis sdk with samples: [link](https://drive.google.com/file/d/1cStacI6XL9zFIHL4PtAu_gnk9EDLNd8H/view?usp=sharing)
Yuris sdk with emote: [link](https://drive.google.com/file/d/1TPTiBz6JKNRRKp3pQCUexVfNXZFxUG16/view?usp=sharing)

**Comment by 2439905184** [comment]
Yes.Just arhive them like what the library (博物馆)do.
This repo do not have English version.
I think it is good to make english.readme.md.
But I do not always have lots of free time.

**Comment by 2439905184** [comment]
Thanks for you opening this issue .
Toomorrow I will have a look.

**Comment by 2439905184** [comment]
suika2 engine is oepnsource. So I think it is needn't to achive it.
I have joined their discord.
I will achive engines if I think they may get lost in the future on internet.

**Comment by Cosetto** [comment]
Good news, my friend is gonna reupload all the engine mentioned in the image but it will take him 2 days because all of them are 60gb and electricity problem

**Comment by 2439905184** [comment]
> Good news, my friend is gonna reupload all the engine mentioned in the image but it will take him 2 days because all of them are 60gb and electricity problem

thanks

**Comment by Cosetto** [comment]
@2439905184 do you use FTP? My friend said he uploaded to it 
![image](https://user-images.githubusercontent.com/81801486/181918115-ff945da5-a035-4cac-858f-8e6eac3710f3.png)

**Comment by 2439905184** [comment]
![image](https://user-images.githubusercontent.com/29478722/182004700-4070c21d-5542-41fa-adc6-4273247eac95.png)

**Comment by 2439905184** [comment]
I think I should try vpn

**Comment by 2439905184** [comment]
Seems I still can't connect to this ftp.
Did him close the ftp server?

**Comment by Cosetto** [comment]
![image](https://user-images.githubusercontent.com/81801486/182005317-1a6549d4-6207-4c0d-bce5-5b6d30409525.png)
Nope, I still got it

> @2439905184 do you use FTP? My friend said he uploaded to it ![image](https://user-images.githubusercontent.com/81801486/181918115-ff945da5-a035-4cac-858f-8e6eac3710f3.png) Host: haru.celatos.com Username: Arianrhod Pass: IcyEngine15@ Port: 2121

@2439905184 oops the username should be: Adrianrhod not Arianrhod

**Comment by Crystlia** [comment]
> > @2439905184 do you use FTP? My friend said he uploaded to it ![image](https://user-images.githubusercontent.com/81801486/181918115-ff945da5-a035-4cac-858f-8e6eac3710f3.png) Host: haru.celatos.com Username: Arianrhod Pass: IcyEngine15@ Port: 2121
> 
> @2439905184 oops the username should be: Adrianrhod not Arianrhod

Brother, there is a MalieSDK in this FTP, but it requires a password. I couldn't find the password anywhere. Could you please provide the password?

**Comment by Crystlia** [comment]
> > @2439905184 do you use FTP? My friend said he uploaded to it ![image](https://user-images.githubusercontent.com/81801486/181918115-ff945da5-a035-4cac-858f-8e6eac3710f3.png) Host: haru.celatos.com Username: Arianrhod Pass: IcyEngine15@ Port: 2121
> 
> @2439905184 oops the username should be: Adrianrhod not Arianrhod

Bro, there is a MalieSDK in this FTP, but it requires a password. I couldn't find the password anywhere. Could you please provide the password?

**Comment by koukdw** [comment]
> > > @2439905184 do you use FTP? My friend said he uploaded to it ![image](https://user-images.githubusercontent.com/81801486/181918115-ff945da5-a035-4cac-858f-8e6eac3710f3.png) Host: haru.celatos.com Username: Arianrhod Pass: IcyEngine15@ Port: 2121
> > 
> > 
> > @2439905184 oops the username should be: Adrianrhod not Arianrhod
> 
> Bro, there is a MalieSDK in this FTP, but it requires a password. I couldn't find the password anywhere. Could you please provide the password?

I don't have the password but i downloaded the dev kit just to see if i didnt have that already. Turns out i already had this stuff.
You can easily get the dev kit by downloading Dies Irae for Switch and extracting the romfs of the nsp

**Comment by Crystlia** [comment]
> > > > @2439905184 do you use FTP? My friend said he uploaded to it ![image](https://user-images.githubusercontent.com/81801486/181918115-ff945da5-a035-4cac-858f-8e6eac3710f3.png) Host: haru.celatos.com Username: Arianrhod Pass: IcyEngine15@ Port: 2121
> > > 
> > > 
> > > @2439905184 oops the username should be: Adrianrhod not Arianrhod
> > 
> > 
> > Bro, there is a MalieSDK in this FTP, but it requires a password. I couldn't find the password anywhere. Could you please provide the password?
> 
> I don't have the password but i downloaded the dev kit just to see if i didnt have that already. Turns out i already had this stuff. You can easily get the dev kit by downloading Dies Irae for Switch and extracting the romfs of the nsp

I have obtained the data using your method, thank you very much.

**Comment by Cosetto** [comment]
Anybody have Kud Wafter source code?
