### ISSUE TITLE
请大佬来看看这个galgame是用什么引擎的

### ISSUE THREAD

**Issue by onecatcute** [2439905184/Galgame-Engine-Collect#38]
游戏名：彼女×彼女×彼女～三姉妹とのドキドキ共同生活～
<img width="517" alt="后缀" src="https://user-images.githubusercontent.com/104288921/197719438-739ff8e6-9961-4900-b685-ca9e73142da2.PNG">
游戏文件没有后缀名，用Garbro提取游戏文本dat01，解压出来的文件后缀名是.adv
<img width="535" alt="ADV" src="https://user-images.githubusercontent.com/104288921/197719776-eb1002ba-caf7-4e16-a5a0-65e705e7b13f.PNG">
大佬做的《引擎格式大全和引擎大全》里的Signature，我不知道从何辨别，之后厚着脸皮向大佬请教，还望大佬解答。

**Comment by 2439905184** [comment]
已收到消息, 等我有空的话来看一下

**Comment by Cosetto** [comment]
The engine is AST base on GARbro's database, it's almost like QLIE. To pack the files back to those extensionless dat0X use [arc_conv](https://github.com/amayra/arc_conv). 
The command should be: **arc_conv.exe --pack arc12 <in_foldder> <output_file> <1 or 2>**
Check the header of the dat0X first, if it is ARC2, the number above should be 2 
![image](https://user-images.githubusercontent.com/81801486/200717620-041c94c9-6950-4429-ad16-6e2332712bf6.png)

**Comment by Cosetto** [comment]
The reason why I said it's like Qlie because you can adjust the archives the engine reads in the **System** file
![image](https://user-images.githubusercontent.com/81801486/200718106-b232a71d-f4d5-480b-8f1c-24943122d2b8.png)

**Comment by onecatcute** [comment]
Nice. You solved my big trouble. Thanks for you help.
